services:
  review:
    image: docker.io/library/python
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - .:/app
      - /home/example/Pictures:/files/Pictures
    ports:
      - 8000:8000
    command:
      - python
      - /app/gallery.py
      - /files
      - --host
      - 0.0.0.0
