name: Docker

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-push:
    name: Build and push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - dockerfile: Dockerfile
            tag: latest
          - dockerfile: Dockerfile.gltf
            tag: gltf

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            alanaktion/gallery:${{ matrix.tag }}
            ghcr.io/alanaktion/gallery:${{ matrix.tag }}
          cache-from: type=gha,scope=${{ matrix.tag }}
          cache-to: type=gha,mode=max,scope=${{ matrix.tag }}
